//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMom
    {
        public int MomID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual tblProjectInfo tblProjectInfo { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
    }
}
