//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectInfo
    {
        public tblProjectInfo()
        {
            this.tblMoms = new HashSet<tblMom>();
            this.tblUserInfoes = new HashSet<tblUserInfo>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<tblMom> tblMoms { get; set; }
        public virtual ICollection<tblUserInfo> tblUserInfoes { get; set; }
    }
}
