//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserInfo
    {
        public tblUserInfo()
        {
            this.tblMoms = new HashSet<tblMom>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual ICollection<tblMom> tblMoms { get; set; }
        public virtual tblProjectInfo tblProjectInfo { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
